// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gap_fill.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGapFill = `-- name: CreateGapFill :one
INSERT INTO gap_fill (period_id, day, start_utc, end_utc, category_id, note, description, source)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at, description
`

type CreateGapFillParams struct {
	PeriodID    int64         `json:"period_id"`
	Day         string        `json:"day"`
	StartUtc    string        `json:"start_utc"`
	EndUtc      string        `json:"end_utc"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	Note        string        `json:"note"`
	Description string        `json:"description"`
	Source      string        `json:"source"`
}

func (q *Queries) CreateGapFill(ctx context.Context, arg CreateGapFillParams) (GapFill, error) {
	row := q.db.QueryRowContext(ctx, createGapFill,
		arg.PeriodID,
		arg.Day,
		arg.StartUtc,
		arg.EndUtc,
		arg.CategoryID,
		arg.Note,
		arg.Description,
		arg.Source,
	)
	var i GapFill
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Day,
		&i.StartUtc,
		&i.EndUtc,
		&i.CategoryID,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const deleteGapFill = `-- name: DeleteGapFill :execrows
DELETE FROM gap_fill WHERE id = ? AND period_id = ?
`

type DeleteGapFillParams struct {
	ID       int64 `json:"id"`
	PeriodID int64 `json:"period_id"`
}

func (q *Queries) DeleteGapFill(ctx context.Context, arg DeleteGapFillParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGapFill, arg.ID, arg.PeriodID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listGapFillsForDay = `-- name: ListGapFillsForDay :many
SELECT id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at, description FROM gap_fill WHERE period_id = ? AND day = ? ORDER BY start_utc
`

type ListGapFillsForDayParams struct {
	PeriodID int64  `json:"period_id"`
	Day      string `json:"day"`
}

func (q *Queries) ListGapFillsForDay(ctx context.Context, arg ListGapFillsForDayParams) ([]GapFill, error) {
	rows, err := q.db.QueryContext(ctx, listGapFillsForDay, arg.PeriodID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GapFill{}
	for rows.Next() {
		var i GapFill
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Day,
			&i.StartUtc,
			&i.EndUtc,
			&i.CategoryID,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGapFillsForPeriod = `-- name: ListGapFillsForPeriod :many
SELECT id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at, description FROM gap_fill WHERE period_id = ? ORDER BY day, start_utc
`

func (q *Queries) ListGapFillsForPeriod(ctx context.Context, periodID int64) ([]GapFill, error) {
	rows, err := q.db.QueryContext(ctx, listGapFillsForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GapFill{}
	for rows.Next() {
		var i GapFill
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Day,
			&i.StartUtc,
			&i.EndUtc,
			&i.CategoryID,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGapFill = `-- name: UpdateGapFill :one
UPDATE gap_fill SET
    day         = ?,
    start_utc   = ?,
    end_utc     = ?,
    category_id = ?,
    note        = ?,
    description = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND period_id = ?
RETURNING id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at, description
`

type UpdateGapFillParams struct {
	Day         string        `json:"day"`
	StartUtc    string        `json:"start_utc"`
	EndUtc      string        `json:"end_utc"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	Note        string        `json:"note"`
	Description string        `json:"description"`
	ID          int64         `json:"id"`
	PeriodID    int64         `json:"period_id"`
}

func (q *Queries) UpdateGapFill(ctx context.Context, arg UpdateGapFillParams) (GapFill, error) {
	row := q.db.QueryRowContext(ctx, updateGapFill,
		arg.Day,
		arg.StartUtc,
		arg.EndUtc,
		arg.CategoryID,
		arg.Note,
		arg.Description,
		arg.ID,
		arg.PeriodID,
	)
	var i GapFill
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Day,
		&i.StartUtc,
		&i.EndUtc,
		&i.CategoryID,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const updateGapFillSpan = `-- name: UpdateGapFillSpan :one
UPDATE gap_fill SET
    start_utc   = ?,
    end_utc     = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND period_id = ?
RETURNING id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at, description
`

type UpdateGapFillSpanParams struct {
	StartUtc string `json:"start_utc"`
	EndUtc   string `json:"end_utc"`
	ID       int64  `json:"id"`
	PeriodID int64  `json:"period_id"`
}

func (q *Queries) UpdateGapFillSpan(ctx context.Context, arg UpdateGapFillSpanParams) (GapFill, error) {
	row := q.db.QueryRowContext(ctx, updateGapFillSpan,
		arg.StartUtc,
		arg.EndUtc,
		arg.ID,
		arg.PeriodID,
	)
	var i GapFill
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Day,
		&i.StartUtc,
		&i.EndUtc,
		&i.CategoryID,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}
