// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slack_channel.sql

package sqlc

import (
	"context"
)

const deleteSlackChannelsByAccount = `-- name: DeleteSlackChannelsByAccount :exec
DELETE FROM slack_channel WHERE account_id = ?
`

func (q *Queries) DeleteSlackChannelsByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteSlackChannelsByAccount, accountID)
	return err
}

const getSlackChannel = `-- name: GetSlackChannel :one
SELECT id, account_id, external_id, name, is_private, selected, created_at FROM slack_channel WHERE id = ?
`

func (q *Queries) GetSlackChannel(ctx context.Context, id int64) (SlackChannel, error) {
	row := q.db.QueryRowContext(ctx, getSlackChannel, id)
	var i SlackChannel
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExternalID,
		&i.Name,
		&i.IsPrivate,
		&i.Selected,
		&i.CreatedAt,
	)
	return i, err
}

const listSelectedSlackChannels = `-- name: ListSelectedSlackChannels :many
SELECT id, account_id, external_id, name, is_private, selected, created_at FROM slack_channel WHERE selected = 1 ORDER BY name
`

func (q *Queries) ListSelectedSlackChannels(ctx context.Context) ([]SlackChannel, error) {
	rows, err := q.db.QueryContext(ctx, listSelectedSlackChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackChannel{}
	for rows.Next() {
		var i SlackChannel
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Name,
			&i.IsPrivate,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackChannels = `-- name: ListSlackChannels :many
SELECT id, account_id, external_id, name, is_private, selected, created_at FROM slack_channel ORDER BY name
`

func (q *Queries) ListSlackChannels(ctx context.Context) ([]SlackChannel, error) {
	rows, err := q.db.QueryContext(ctx, listSlackChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackChannel{}
	for rows.Next() {
		var i SlackChannel
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Name,
			&i.IsPrivate,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackChannelsByAccount = `-- name: ListSlackChannelsByAccount :many
SELECT id, account_id, external_id, name, is_private, selected, created_at FROM slack_channel WHERE account_id = ? ORDER BY name
`

func (q *Queries) ListSlackChannelsByAccount(ctx context.Context, accountID string) ([]SlackChannel, error) {
	rows, err := q.db.QueryContext(ctx, listSlackChannelsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackChannel{}
	for rows.Next() {
		var i SlackChannel
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Name,
			&i.IsPrivate,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSlackChannelSelected = `-- name: SetSlackChannelSelected :exec
UPDATE slack_channel SET selected = ? WHERE id = ?
`

type SetSlackChannelSelectedParams struct {
	Selected int64 `json:"selected"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetSlackChannelSelected(ctx context.Context, arg SetSlackChannelSelectedParams) error {
	_, err := q.db.ExecContext(ctx, setSlackChannelSelected, arg.Selected, arg.ID)
	return err
}

const upsertSlackChannel = `-- name: UpsertSlackChannel :one
INSERT INTO slack_channel (account_id, external_id, name, is_private, selected)
VALUES (?, ?, ?, ?, CASE WHEN ? = 1 THEN 1 ELSE 0 END)
ON CONFLICT (account_id, external_id) DO UPDATE SET
    name = excluded.name,
    is_private = excluded.is_private
RETURNING id, account_id, external_id, name, is_private, selected, created_at
`

type UpsertSlackChannelParams struct {
	AccountID  string      `json:"account_id"`
	ExternalID string      `json:"external_id"`
	Name       string      `json:"name"`
	IsPrivate  int64       `json:"is_private"`
	Column5    interface{} `json:"column_5"`
}

func (q *Queries) UpsertSlackChannel(ctx context.Context, arg UpsertSlackChannelParams) (SlackChannel, error) {
	row := q.db.QueryRowContext(ctx, upsertSlackChannel,
		arg.AccountID,
		arg.ExternalID,
		arg.Name,
		arg.IsPrivate,
		arg.Column5,
	)
	var i SlackChannel
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExternalID,
		&i.Name,
		&i.IsPrivate,
		&i.Selected,
		&i.CreatedAt,
	)
	return i, err
}
